CREATE DATABASE AWS_COURSE_DB

CREATE TABLE VEHICLES (
    ID INTEGER PRIMARY KEY,
    NAME VARCHAR(100),
    PRICE INTEGER
)

INSERT INTO VEHICLES VALUES(1, "ZAZ Lanos", 100000);
INSERT INTO VEHICLES VALUES(1, "Honda Civic", 5000);
INSERT INTO VEHICLES VALUES(1, "Skoda Octavia", 2);

SELECT * FROM VEHICLES;